function okboomer() {
    let ye1 = parseFloat(document.getElementById("year1").value);
    let inter = parseFloat(document.getElementById("inter").value);
    let ye2 = ye1 + inter;
    let ye3 = ye2 + inter;
    let ye4 = ye3 + inter;
    let ye5 = ye4 + inter;
    let y1 = parseFloat(document.getElementById("sales1").value);
    let y2 = parseFloat(document.getElementById("sales2").value);
    let y3 = parseFloat(document.getElementById("sales3").value);
    let y4 = parseFloat(document.getElementById("sales4").value);
    let y5 = parseFloat(document.getElementById("sales5").value);
    let m, c;
    let x1, x2, x3, x4, x5;
    x1 = (ye1 - ye3) / inter;
    x2 = (ye2 - ye3) / inter;
    x3 = (ye3 - ye3) / inter;
    x4 = (ye4 - ye3) / inter;
    x5 = (ye5 - ye3) / inter;
    let ex = 0;
    let exy = x1 * y1 + x2 * y2 + x3 * y3 + x4 * y4 + x5 * y5;
    ex2 = x1 * x1 + x2 * x2 + x3 * x3 + x4 * x4 + x5 * x5;
    ey = y1 + y2 + y3 + y4 + y5;
    m = exy / ex2;
    c = ey / 5;

    //log anwer ok man
    console.log("working.....");
    console.log("Year Data");
    console.log(ye1);
    console.log(ye2);
    console.log(ye3);
    console.log(ye4);
    console.log(ye5);
    console.log("Sales data");
    console.log(y1);
    console.log(y2);
    console.log(y3);
    console.log(y4);
    console.log(y5);
    console.log("x data");
    console.log(x1);
    console.log(x2);
    console.log(x3);
    console.log(x4);
    console.log(x5);
    console.log("Other data");
    console.log("ex = " + ex);
    console.log("exy = " + exy);
    console.log("ex2 = " + ex2);
    console.log("m = " + m);
    console.log("c = " + c);
    console.log("ey = " + ey);
    //anser here
    document.getElementById("equation").innerHTML = "y = " + m + "x +" + c;
    //y = mx + c
    let trend1, trend2, trend3, trend4, trend5;
    trend1 = (m * x1) + c;
    trend2 = (m * x2) + c;
    trend3 = (m * x3) + c;
    trend4 = (m * x4) + c;
    trend5 = (m * x5) + c;
    let tdtot = trend1 + trend2 + trend3 + trend4 + trend5;
    console.log("td total = " + tdtot);
    document.getElementById("yearr1").innerHTML = ye1;
    document.getElementById("yearr2").innerHTML = ye2;
    document.getElementById("yearr3").innerHTML = ye3;
    document.getElementById("yearr4").innerHTML = ye4;
    document.getElementById("yearr5").innerHTML = ye5;
    document.getElementById("saless1").innerHTML = y1;
    document.getElementById("saless2").innerHTML = y2;
    document.getElementById("saless3").innerHTML = y3;
    document.getElementById("saless4").innerHTML = y4;
    document.getElementById("saless5").innerHTML = y5;
    document.getElementById("xx1").innerHTML = x1;
    document.getElementById("xx2").innerHTML = x2;
    document.getElementById("xx3").innerHTML = x3;
    document.getElementById("xx4").innerHTML = x4;
    document.getElementById("xx5").innerHTML = x5;
    document.getElementById("xxx1").innerHTML = x1 * x1;
    document.getElementById("xxx2").innerHTML = x2 * x2;
    document.getElementById("xxx3").innerHTML = x3 * x3;
    document.getElementById("xxx4").innerHTML = x4 * x4;
    document.getElementById("xxx5").innerHTML = x5 * x5;
    document.getElementById("td1").innerHTML = trend1;
    document.getElementById("td2").innerHTML = trend2;
    document.getElementById("td3").innerHTML = trend3;
    document.getElementById("td4").innerHTML = trend4;
    document.getElementById("td5").innerHTML = trend5;
    document.getElementById("xxyy1").innerHTML = x1 * y1;
    document.getElementById("xxyy2").innerHTML = x2 * y2;
    document.getElementById("xxyy3").innerHTML = x3 * y3;
    document.getElementById("xxyy4").innerHTML = x4 * y4;
    document.getElementById("xxyy5").innerHTML = x5 * y5;
    document.getElementById("yetotal").innerHTML = "NOP";
    document.getElementById("satotal").innerHTML = "total = " + ey;
    document.getElementById("xx1total").innerHTML = "total = " + ex;
    document.getElementById("xxx1total").innerHTML = "total = " + ex2;
    document.getElementById("tdtotal").innerHTML = "total = " + tdtot;
    document.getElementById("xxyytotal").innerHTML = "total = " + exy;
    document.getElementById("valuem").innerHTML = "M = " + m;
    document.getElementById("valuey").innerHTML = "C = " + c;
    //chart start here

}